sources:
  - name: Covid
    handler:
      graphql:
        endpoint: https://covid.aibaobao.club/
  - name: Polulation 
    handler:
      graphql:
        endpoint: https://population.aibaobao.club/
transforms:
  - extend: |
      extend type Country {
        deathRate: Float
        population: Float
      }
#       extend type Query {
#         stat(country: String!): Stat
#       }
#       type Stat {
#         confirmedRatio: Float
#         deathRatio: Float
#         recoveredRatio: Float
#         case: Case
#         population: ApiPopulation
#       }
additionalResolvers:
  - ./src/case-resolvers.js
#  - ./src/case-additional-resolvers.js
#   - ./src/query-additional-resolvers.js