sources:
  - name: Covid
    handler:
      graphql:
        endpoint: https://covid.aibaobao.club/
  - name: Polulation 
    handler:
      graphql:
        endpoint: https://population.aibaobao.club/
# transforms:
#   - extend: |
#       extend type Country {
#         deathRate: Float
#         population: Float
#       }
# additionalResolvers:
#   - ./src/case-resolvers.js